owner: GoodMorninTech
repo: status

sites:
  - name: Good Morning Tech website
    url: https://goodmorningtech.news
    icon: https://cdn.goodmorningtech.news/tsp-logo.png
    
  - name: Development website
    url: https://dev.goodmorningtech.news
    icon: https://cdn.goodmorningtech.news/tsp-logo.png
    
  - name: Source BBC
    url: https://feeds.bbci.co.uk/news/technology/rss.xml
  - name: Source TechCrunch
    url: https://techcrunch.com/feed/
  - name: Source The Verge
    url: https://www.theverge.com/rss/index.xml
  - name: Source The Guardian
    url: https://www.theguardian.com/uk/technology/rss
  - name: Source CNN
    url: http://rss.cnn.com/rss/cnn_tech.rss

status-website:
  cname: status.goodmorningtech.news
  theme: light
  title: Status Good Morning Tech
  css: "#sapper > nav > div > div > a > div {display: none;}"
  logoUrl: https://cdn.goodmorningtech.news/logo.png
  favicon: https://cdn.goodmorningtech.news/tsp-logo.png
  introTitle: Status Good Morning Tech

i18n:
  footer: This status page is from the Good Morning Tech Team, powered by [Upptime](https://upptime.js.org)
