owner: GoodMorninTech
repo: status

sites:
  - name: Good Morning Tech website
    url: https://goodmorningtech.news
    icon: https://cdn.goodmorningtech.news/tsp-logo.png
    
  - name: Development website
    url: https://dev.goodmorningtech.news
    icon: https://cdn.goodmorningtech.news/tsp-logo.png

  - name: CDN Good Morning Tech
    url: https://cdn.goodmorningtech.news
    icon: https://cdn.goodmorningtech.news/tsp-logo.png
    
  - name: GitHub Trending
    url: https://github.com/trending
    icon: https://cdn.goodmorningtech.news/website/github-mark.svg
    
  - name: Leetcode
    url: https://leetcode.com
    icon: https://leetcode.com/static/images/LeetCode_logo_rvs.png
    
  - name: Cybrancee
    url: https://webhosting.cybrancee.com:8443/
    icon: https://cybrancee.com/client/templates/lagom2/assets/img/favicons/favicon-192.png
    
  - name: Source BBC
    url: https://feeds.bbci.co.uk/news/technology/rss.xml
    icon: http://cdn.goodmorningtech.news/website/news_source_icons/bbc.svg
  - name: Source TechCrunch
    url: https://techcrunch.com/feed/
    icon: http://cdn.goodmorningtech.news/website/news_source_icons/techcrunch.svg
  - name: Source The Verge
    url: https://www.theverge.com/rss/index.xml
    icon: http://cdn.goodmorningtech.news/website/news_source_icons/verge.svg
  - name: Source The Guardian
    url: https://www.theguardian.com/uk/technology/rss
    icon: http://cdn.goodmorningtech.news/website/news_source_icons/guardian.svg
  - name: Source CNN
    url: http://rss.cnn.com/rss/cnn_tech.rss
    icon: http://cdn.goodmorningtech.news/website/news_source_icons/cnn.svg

status-website:
  cname: status.goodmorningtech.news
  theme: light
  name: Status Good Morning Tech
  css: "#sapper > nav > div > div > a > div {display: none;}"
  logoUrl: https://cdn.goodmorningtech.news/logo.png
  favicon: https://cdn.goodmorningtech.news/tsp-logo.png
  introTitle: Status Good Morning Tech

i18n:
  footer: This status page is from the Good Morning Tech Team, powered by [Upptime](https://upptime.js.org)
